// main.c

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"
#include "systick.h"
#include "uart.h"
#include "tim.h"
#include "exti.h"


// symbolic names:
#define GPIOAEN    (1U<<0)		// GPIOAEN : set bit 0 as a 1
#define PIN5       (1U<<5)		// PIN5    : set bit 5 as a 1
#define LED_PIN	PIN5			// LED_PIN : set led pin as a pin5


/* function prototype */
static void exti_callback(void);


int main(void){


	// enables the AHB1 enable register by bitwise or'ing with a set of bits that are all 0 except for bit 0
	RCC->AHB1ENR |= GPIOAEN;

	// sets the Mode register of GPIO port as a 1 in bit 10 and a 0 in but 11
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);
	// this is 01 = Mode = set as output pin


	// call pc13 exti init function
	pc13_exti_init();

	// call function to enable uart2
	uart2_tx_init();

	tim2_1hz_init();



	while(1){



	}


	return (0);

}



// this should be a static function which:
// print a statment to serial ouput saying button has been pressed
// and toggle LED
static void exti_callback(void){

	// print statment
	printf("Btn Pressed!\n\r");

	// toggle LED
	GPIOA->ODR ^= LED_PIN;


}






// we have to call this exaxtly named function becasue it is what is defined in our vector table
// to find our vector table we go to our project tree and look at our startup folder
// then we scroll down to g_pfnVectors and look for the interrupt handler that we are using/looking for
// we then define a void-void function using the name provided for our interrupt
// not the comment [15:10], meaning it works for lines 10 - 15
// since we are interested in line 13 create a macro for it in our exti.h file
// this macro is for the exti pending register and this is what we will be analzing for when trigger occured
//
void EXTI15_10_IRQHandler(void){

	if((EXTI->PR & EXTIPR13/* Check the exti pending register flag if it has been set to 1 in the designanted register */) != 0)
	{	TIM2->SR &=~SR_UIF;
		// this is usually a callback function
		exti_callback();
		while(!(TIM2->SR & SR_UIF)){printf("We in the timer loop\n\r");}
	// clear PR Flag to rearm it
		EXTI->PR |= EXTIPR13;
		// toggle LED
		GPIOA->ODR ^= LED_PIN;


	}


















}
