/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>
#include <stdbool.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"

#include "uart.h"

#define GPIOAEN			(1U<<0)
#define GPIOA_5			(1U<<5)

#define LED_PIN			GPIOA_5

static void usart2_interrupt_callback(void);



char key;


// Creating finite state enum to keep track of what state we are in, in the sequence
// very similar to our sequence recognizer problems in Computer Arch.
typedef enum {
    WAITING_FOR_C,
    WAITING_FOR_O,
    WAITING_FOR_D
} State_t;

// global state
State_t currentState = WAITING_FOR_C;


int main(void){


	// enabling clock access to the led
	RCC->AHB1ENR |= GPIOAEN;

	// set led to output pin
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &=~(1U<<11);


	uart2_rx_interrupt_init();


	while(1){

	}


	return (0);

}


static void usart2_interrupt_callback(void){

	char key = USART2->DR; // Read ONLY ONCE per interrupt

	switch (currentState) {
    	case WAITING_FOR_C:
    		if (key == 'c'){currentState = WAITING_FOR_O;}
    		else{GPIOA->ODR &=~LED_PIN;}
    		break;

    	case WAITING_FOR_O:
    		if (key == 'o') currentState = WAITING_FOR_D;
    		else if (key == 'c') currentState = WAITING_FOR_O; // Handle "cc"
    		else currentState = WAITING_FOR_C;
    		break;

    	case WAITING_FOR_D:
    		if (key == 'd') {
    			GPIOA->ODR |= LED_PIN; // Success!
    			currentState = WAITING_FOR_C; // Reset for next time
    		}else if (key == 'c') {
    			currentState = WAITING_FOR_O;
    		}else {
    			currentState = WAITING_FOR_C;
    		}
    		break;
}
}



void USART2_IRQHandler(void){


	if(USART2->SR & SR_RXNE){

		// callback function
		usart2_interrupt_callback();
	}





}


