/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"
#include "systick.h"
#include "uart.h"
#include "tim.h"

int timestamp = 0;




int main(void){

	tim2_output_compare_pa5();
	tim3_pa6_input_capture();


	while(1){

		/* wait until edge is captured */
		while(!(TIM3->SR & SR_CC1IF)){} // loop until set


		// read captured couter value
		timestamp = TIM3->CCR1;

		// let then tim2 be our source
		// this is done comparing a capture value
		// for PA5 to PA6


	}


	return (0);

}


