/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 * purpose:        : blink led
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


// Where is led connected?
// Port: A
// Pin:  5


// symbolic name for the starting address of our peripherals mem block
#define PERIPH_BASE			(0x40000000UL)

// offset calculated from base
#define AHB1PERIPH_OFFSET 	(0x00020000UL)


// this is equal to the PERIPH_BASE + OFFSET
#define AHB1PERIPH_BASE		(PERIPH_BASE + AHB1PERIPH_OFFSET)

#define GPIOA_OFFSET		(0x00000000UL)

#define GPIOA_BASE			(AHB1PERIPH_BASE + GPIOA_OFFSET)

#define RCC_OFFSET			(0x3800UL)

#define RCC_BASE			(RCC_OFFSET + AHB1PERIPH_BASE)

#define AHB1EN_R_OFFSET		(0x30UL)
#define RCC_AHB1_R			(*(volatile unsigned int*)(RCC_BASE + AHB1EN_R_OFFSET))


#define MODE_R_OFFSET		(0x00UL)
#define GPIO_MODE_R			(*(volatile unsigned int*)(GPIOA_BASE + MODE_R_OFFSET))


							// this means shift 1 at position 0
#define GPIOAEN				(1U<<0) // 0b 0000 0000 0000 0000 0000 0000 0000 0001


#define OD_R_OFFSET			(0x14UL)
#define GPIOA_OD_R			(*(volatile unsigned int*)(GPIOA_BASE + OD_R_OFFSET))

#define PIN5				(1U<<5)
#define LED_PIN				PIN5




/*
 * using tilde means invert
 *
 * 	here we set bit 10 to 1                                                                       :  (1U<<10)
 * 	here we set bit 11 to 1 and invert to set it to 0 and do and operation so only bit 11 changes : &=~(1U<<11)
 *
 *
 *
 * */


// 0x4000 000 + 0x0002 0000 = 0x4002 0000



int main(void){





	// Step 1: Enable Clock access to GPIOA
	RCC_AHB1_R |= GPIOAEN;



	// Step 2: Set PA5 as output pin

	GPIO_MODE_R |= (1U<<10);    // setting bit 10 to 1
	GPIO_MODE_R &=~(1U<<11);    // setting bit 11 to 0


	while(1){


	// Step 3: set PA5 HIGH
	//GPIOA_OD_R |= LED_PIN;


	/* Step 4: Toggle pa5   */

	// note: the '^' is the toggle operator


	GPIOA_OD_R ^= LED_PIN;


	// this is for loop for delaying so we can actually see the LED get toggled
	for(int i = 0; i < 1000000; i++){


	}




	}




	return (0);





}


