/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"

#include "uart.h"
#include "adc.h"


volatile uint32_t sensorValue;


int main(void){

	// enable PA1 ADC input
	pa1_adc_init();
	uart2_rxtx_init();



	while(1){


		// enable conversion of ADC
		start_conversion();

		sensorValue = read_adc();

		// print out conversion
		printf("Output: %ld\n\r", sensorValue);

	}


	return (0);

}


