/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"
#include "systick.h"
#include "uart.h"
#include "tim.h"

// symbolic names:
#define GPIOAEN    (1U<<0)		// GPIOAEN : set bit 0 as a 1
#define PIN5       (1U<<5)		// PIN5    : set bit 5 as a 1
#define LED_PIN	PIN5			// LED_PIN : set led pin as a pin5

#define HISR_TCIF6     (1U<<21) // transfer complete interrupt flag



/* function prototype */
void DMA1_Channel6_IRQHandler(void);
static void callback(void);
int readInputFromUser(char* input);



int main(void){


	char message2[BUFSIZ];

	// enables the AHB1 enable register by bitwise or'ing with a set of bits that are all 0 except for bit 0
	RCC->AHB1ENR |= GPIOAEN;

	// sets the Mode register of GPIO port as a 1 in bit 10 and a 0 in but 11
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);
	// this is 01 = Mode = set as output pin

	// size of the input message from the user
	int sizeMsg = 0;

	// enable uart2 for receive and transmit
	uart2_rxtx_init();

	// get input from user and put into our string and store the size of the string
	sizeMsg = readInputFromUser(message2);


	// initialize dma1 stream 6 and print the message input from the user
	dma1_stream6_init((uint32_t) message2, (uint32_t) &USART2->DR , sizeMsg);

	while(1){


		}





	return (0);

}

/*======================================*
 *  function: readInputFromUser     	*
 *  									*
 *  return val: int						*
 *  parameters: char*	 				*
 * 										*
 * 	purpose: this function is supposed  *
 *  to write to a string and return the *
 *  the size of string    				*
 *    									*
 *======================================*/

int readInputFromUser(char* input)
{

	int i = 0;

	printf("What would you like to print!\r\n");
	printf("Type \\q when you are done inputting your word\r\n");
	char quitCheck[2] = "XX";
	printf("\r\n");


	while((quitCheck[0] != '\\') && (quitCheck[1] != 'q')){


		char inputChar = uart2_read();
		input[i] = inputChar;
		printf(">>%c\r\n", inputChar);
		if(i == 0){
		quitCheck[0] = input[i];
		}else if(i == 1){
			quitCheck[1] = input[i];

		}
		else{
			quitCheck[0] = input[i-1];
			quitCheck[1] = input[i];

		}


		i++;


	}


	input[i-2] = '\r';
	input[i-1] = '\n';
	return i;






}




static void callback(void)
{

	GPIOA->ODR ^= LED_PIN;

}



void DMA1_Stream6_IRQHandler(void)
{

	/* check if flag has been set for dma1 stream 6 */
	if(DMA1->HISR & HISR_TCIF6){

		// reset flag
		DMA1->HIFCR |= HISR_TCIF6;

		callback();


	}


}



