/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"

#include "uart.h"

uint32_t sensorValue;



int main(void){






	/* enable ability to use printf */
	uart2_rxtx_init();

	/* turning on adc interrupt via the pa1 periph */
	pa1_adc_interrupt_init();

	/* start Analog to digitial conversion */
	// can't forget this part!!!
	// remember DUDE that there are no free lunches
	// everything has to be turned on here
	// DONT FORGET!!!!
	start_conversion();






	while(1){
//		start_conversion();
//		sensorValue = adc_read();
//		printf("Sensor value: %d\n\r", (volatile int)sensorValue);

	}


	return (0);

}




static void adc_callback(void){

	for(int i = 0; i < 1000000; i ++){};


	sensorValue = (ADC1->DR);
	printf("Sensor value: %d\n\r", (volatile int)sensorValue);


}



void ADC_IRQHandler(void){



	// need to check if end of conversion has happened
	if((ADC1->SR & /*EOC bit is 1*/ SR_EOC) != 0){


		// clear EOC
		ADC1->SR &=~ (SR_EOC);

		// do some shit boy
		adc_callback();


	}




}







