/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "stm32f446xx.h"

// self made files
#include "button.h"
#include "led.h"
#include "tim.h"


volatile short button_state = 0;

#define TIM2SRUIF    (1<<0)



int main(void)
{


	// sets up pa1 for output signals
	pa1_output();

	// sets pa0 to receive digital voltage levels
	pa0_input();

	// tim2 init
	tim2_1hz_init();



    /* Loop forever */
	while(1){

		// reads if button has been pressed
		button_state = pa0_read();

		// starts or doesn't start timer depending on if button has been pressed
		tim2_startTimer(button_state);

		if(button_state == 1){

			led_on();
		}

		// checks if timer is done
		if(TIM2->SR & TIM2SRUIF){

			// if timer is done turn led off
			led_off();

			// clear the flag
			TIM2->SR &=~ TIM2SRUIF;

		}
	}
}



