/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"

#include "uart.h"

#define GPIOAEN			(1U<<0)
#define GPIOA_5			(1U<<5)

#define LED_PIN			GPIOA_5

/* function prototype */
static void usart2_callback(void);



char key;

int main(void){


	// enabling clock access to the led
	RCC->AHB1ENR |= GPIOAEN;

	// set led to output pin
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &=~(1U<<11);


	uart2_rx_interrupt_init();


	while(1){}


	return (0);

}



static void usart2_callback(void)
{


		key = USART2->DR;

		if(key == '1'){ // turns pin on if the correct sequence is typed in "b"
			GPIOA->ODR = LED_PIN;

		}else{
			GPIOA->ODR &=~LED_PIN;
		}


}

void USART2_IRQHandler(void)
{

	/* Check if RXNE is set */

	if(USART2->SR & SR_RXNE)
	{
		usart2_callback();

	}



}



