/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"
#include "systick.h"
#include "uart.h"
#include "tim.h"

// symbolic names:
#define GPIOAEN    (1U<<0)		// GPIOAEN : set bit 0 as a 1
#define PIN5       (1U<<5)		// PIN5    : set bit 5 as a 1
#define LED_PIN	PIN5			// LED_PIN : set led pin as a pin5



int main(void){

	// enables the AHB1 enable register by bitwise or'ing with a set of bits that are all 0 except for bit 0
	RCC->AHB1ENR |= GPIOAEN;

	// sets the Mode register of GPIO port as a 1 in bit 10 and a 0 in but 11
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);
	// this is 01 = Mode = set as output pin


	uart2_tx_init();
	tim2_1hz_init();

	while(1){

		// check if UIF flag has been set and stay there until it has been set and then clear it
		while(!(TIM2->SR & SR_UIF)){

			/* Clear  UIF */
			TIM2->SR &=~SR_UIF;

		}


		printf("A second has passed!\n\r");

		// toggle shorthand
		GPIOA->ODR ^= LED_PIN;



	}


	return (0);

}


