/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"

#include "uart.h"
#include "systick.h"

// symbolic names:
#define GPIOAEN    (1U<<0)		// GPIOAEN : set bit 0 as a 1
#define PIN5       (1U<<5)		// PIN5    : set bit 5 as a 1
#define LED_PIN	PIN5			// LED_PIN : set led pin as a pin5
#define GPIOCEN		(1U<<2)     // GPIOCEN : set bit 2 as a 1 to allow clock access to Port C
#define PIN13		(1U<<13)
#define BTN_PIN		PIN13

int main(void){

	// enables the AHB1 enable register by bitwise or'ing with a set of bits that are all 0 except for bit 0
	RCC->AHB1ENR |= GPIOAEN;

	/*    Enable clock access to GPIOA and GPIOC     */
	RCC->AHB1ENR |= GPIOCEN;


	// sets the Mode register of GPIO port as a 1 in bit 10 and a 0 in but 11
	GPIOA->MODER |=(1U<<10);
	GPIOA->MODER &=~(1U<<11);
	// this is 01 = Mode = set as output pin



	/*    Set PC13 as input Pin    */
	GPIOC->MODER &=~(1U<<26);
	GPIOC->MODER &=~(1U<<27);

	// need this function to allow for printing statements
	uart2_rxtx_init();



	printf("About to enter while loop\n\r");





	while(1){

		/*    Check if Button has been pressed   */


		if(GPIOC->IDR & BTN_PIN){ // checks bit 13 of GPIOC_IDR register to see if it is a 1; which would mean button not pressed
			GPIOA->BSRR = (1U<<21);
			printf("Button not pressed\n\r");

		}else{

			printf("Button pressed\n\r");
			GPIOA->BSRR = LED_PIN; // turns on LED
			systickDelayMS(5000);



		}


		}






	return 0;


}


