/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"

#include "uart.h"

#define GPIOAEN			(1U<<0)
#define GPIOA_5			(1U<<5)

#define LED_PIN			GPIOA_5

/* function prototype */
static void usart2_callback(void);



char key;

int main(void){


	// enabling clock access to the led
	RCC->AHB1ENR |= GPIOAEN;

	// set led to output pin
	GPIOA->MODER |= (1U<<10);
	GPIOA->MODER &=~(1U<<11);

	char message[31] = "Hello from Stm32 DMA transfer\n\r";




	uart2_tx_init();
	dam1_stream6_init((uint32_t) message,(uint32_t)&USART2->DR, 31/* length of sourcae */ );



	while(1){}


	return (0);

}



static void dma_callback(void)
{

		GPIOA->ODR = LED_PIN;


}

/* write DMA interrupt handler */
void DMA1_Stream6_IRQHandler(void)
{

	/* check transfer complete interrupt has occured */
	// this is in our DMA1 high status register for stream 6
	if(DMA1->HISR & HISR_TCIF6)
	{

			/* clear flag */
			// check the high fc register
			DMA1->HIFCR |= DMA_HIFCR_CTCIF6;
			// do something
			dma_callback();

}




}



