/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"

#include "uart.h"

uint32_t sensorValue;



int main(void){



	pa1_adc_interrupt_init();


	while(1){


	}


	return (0);

}


static void adc_callback(void){

	sensorValue = (ADC->CDR); // this is changed from calling the function
														 // this is bc an interrupt doesn't need continious checking
	printf("Sensor value: %d \n\r", (int)sensorValue);



}

void ADC_IRQHandler(void)
{
	/* Check for eoc in SR */
	if((ADC1->SR & SR_EOC) != 0)
	{
		/* Clear EOC */
		ADC1->SR &=~ SR_EOC;

		/* Do something */
		adc_callback();

	}

}


