/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"
#include "adc.h"

#include "uart.h"


/* global values */
uint32_t sensorValue = 99;


/* function prototype */
static void adc_callback(void);



int main(void){





// old adc init function:	pa1_adc_init();
	pa1_adc_interupt_init();
	uart2_tx_init();
	start_conversion();

	while(1){


	}


	return (0);

}



static void adc_callback(void){


	// getting value from ADC1 direct register
	sensorValue = ADC1->DR;


	// printing out the value from the DR of the ADC1
	printf("Sensor value: %d \n\r", (volatile int)sensorValue);



}


void ADC_IRQHandler(void){

	/* check for eoc in SR */
	if((ADC1->SR & SR_EOC) != 0/* check adc sr and check if it hasn't been set */)
	{
		/* Clear EOC */
		ADC1->SR &=~ SR_EOC;

		GPIOA->MODER &=~ (1U<11);
		GPIOA->MODER |=  (1U<<10);

		GPIOA->ODR ^= (1U<<5); // toggle LED pin if available


		//call callback function
		adc_callback();

	}



}










