/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

// for using int sizes
#include <stdint.h>
#include <stdio.h>
#include <stdint.h>

// for getting header file for specific board and being able to get all pins and ports
#include "stm32f4xx.h"

#include "uart.h"
#include "adxl345.h"
#include "i2c.h"



/* Defined Macros */
int16_t x, y, z;
float xg, yg, zg;

extern uint8_t dataVals[6];

const float FOUR_G_SCALE_FACT = 0.0078;





int main(void){





	uart2_tx_init();

	I2C2_init();

	I2C2_probe(0x53);
	I2C2_probe(0x1D);

	while(1){}



//		adxl_read_values(DATA_START_ADDR);
//
//		x = ((dataVals[1] << 8)|dataVals[0]);
//		y = ((dataVals[3] << 8)|dataVals[2]);
//		z = ((dataVals[5] << 8)|dataVals[4]);
//
//		xg = x * FOUR_G_SCALE_FACT;
//		yg = y * FOUR_G_SCALE_FACT;
//		zg = z * FOUR_G_SCALE_FACT;
//}






	return (0);

}





